# Yazi configuration file

###############################################################################
# Columns / layout                                                           #
###############################################################################
[mgr]
# Layout ratios (parent : current : preview)
# A 1 : 2 : 3 split makes the current pane roomy, keeps context, and
# reserves generous space for previews on wide terminals.
ratio          = [1, 2, 3]

# File ordering
sort_by        = "natural"   # human-friendly (1, 2, 10 instead of 1,10,2)
sort_dir_first = true        # folders first
sort_reverse   = false       # newest-first? set true if you prefer
sort_sensitive = false       # ignore case

# Visibility flags
show_hidden    = true        # show hidden files and folders
show_symlink   = true        # highlight links in list

# File-list look & feel
linemode       = "mtime"     # prepend modified-time column (size|mtime|permissions)
scrolloff      = 5           # keep 5 rows of context above/below cursor

###############################################################################
# Preview pane                                                               #
###############################################################################
[preview]
max_width      = 600         # don't let previews occupy too much width
max_height     = 900         # reasonable height limit
cache_dir      = ""          # use default cache location
image_filter   = "triangle"  # scaling algorithm for images
image_quality  = 75          # JPEG quality for cached thumbnails

###############################################################################
# File opener rules                                                          #
###############################################################################
[open]
rules = [
	# 1. Directories – simply enter them
	{ name = "*/", use = ["open"] },

	# 2. Plain-text files – open in $EDITOR
	{ mime = "text/*", use = ["edit"] },

	# 3. All other files – use system default
	{ name = "*", use = ["open"] },
]

[opener]
# Open in editor (blocking so you return to the same yazi session)
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "Edit in $EDITOR", block = true, for = "unix" },
]

# System default opener
open = [
	{ run = 'open "$@"', desc = "Open with default app", for = "macos" },
	{ run = 'xdg-open "$@"', desc = "Open with default app", for = "linux" },
]
